### ISSUE TITLE
any chance to make it run on linux?

### ISSUE THREAD

**Issue by assadollahi** [shinyoshiaki/oculus-quest-remote-desktop#6]
It seems the host for the remote desktop is intended to be windows. what would it take to make it run on linux?

**Comment by shinyoshiaki** [comment]
You can run on Linux. You need to build or run yourself.
But desktop sounds not works. Cause by Linux sounds system.

**Comment by shinyoshiaki** [comment]
I built binary for Linux here.
https://github.com/shinyoshiaki/oculus-quest-remote-desktop/releases/tag/alpha-2_linux
